
import os

WAYPOINT_ACCEPTANCE_RADIUS = int(os.environ['WAYPOINT_ACCEPTANCE_RADIUS'])
MINIMUM_BATTERY_TO_START = int(os.environ['MINIMUM_BATTERY_TO_START'])
MINIMUM_BATTERY = int(os.environ['MINIMUM_BATTERY'])
DRONE_ALTITUDE = float(os.environ['DRONE_ALTITUDE'])
MAX_WINDSPEED = float(os.environ['MAX_WINDSPEED'])
FLASK_ENV = os.environ['FLASK_ENV']
WEBSOCKET_SERVER = os.environ['WEBSOCKET_SERVER']
DRONE_IP = os.environ['DRONE_IP']
GROUND_SPEED = 10