from distutils import util
import os

WAYPOINT_ACCEPTANCE_RADIUS = int(os.environ['WAYPOINT_ACCEPTANCE_RADIUS'])
DRONE_ALTITUDE = float(os.environ['DRONE_ALTITUDE'])
MAX_WINDSPEED = float(os.environ['MAX_WINDSPEED'])
FLASK_ENV = os.environ['FLASK_ENV']
WEBSOCKET_SERVER = os.environ['WEBSOCKET_SERVER']
DRONE_IP = os.environ['DRONE_IP']
SERVO_PIN = int(os.environ['SERVO_PIN'])
GROUND_SPEED = 10

BATTERY_USE_VOLTAGE = bool(util.strtobool(os.environ['BATTERY_USE_VOLTAGE']))
MINIMUM_BATTERY = float(os.environ['MINIMUM_BATTERY'])
MINIMUM_BATTERY_TO_START = float(os.environ['MINIMUM_BATTERY_TO_START'])
MINIMUM_BATTERY_PERC = float(os.environ['MINIMUM_BATTERY_PERC'])
MINIMUM_BATTERY_TO_START_PERC = float(os.environ['MINIMUM_BATTERY_TO_START_PERC'])