version: '3.9'
services:
  server:
    build: ./server
    environment:
      - PORT=4000
      - HOST_IP=${HOST_IP}
    restart: always
    network_mode: "host"
    privileged: true
  mavlink:
    build: ./mavlink_controller_server
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_RUN_PORT=5000
      - WEBSOCKET_SERVER=http://localhost:4000
      - DRONE_IP=/dev/bus/usb/001/002
      - WAYPOINT_ACCEPTANCE_RADIUS=5
      - DRONE_ALTITUDE=30
      - MINIMUM_BATTERY=15
      - MINIMUM_BATTERY_TO_START=75
      - MAX_WINDSPEED=8.333333
      - SERVO_PIN=12
    restart: always
    devices:
        - "/dev/bus/usb/001/002"
    network_mode: "host"
    privileged: true
