install:
	pip3 install -r requirements.txt

run:
	python3 ./drone/app.py

runp:
	poetry run python drone/app.py

exp:
	poetry export -f requirements.txt --output requirements.txt

gup:
	git fetch && git pull